apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubeadm-1634"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubeadm-1634"
  template:
    metadata:
      labels:
        app: "kubeadm-1634"
    spec:
      containers:
        - name: "kubeadm-1634"
          image: "luck123.azurecr.io/kubeadm"
          ports:
          - containerPort: 80