apiVersion: v1
kind: Service
metadata:
    name: "kubeadm-1634"
    labels:
        app: "kubeadm-1634"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubeadm-1634"